# Generated by Django 4.2.3 on 2023-07-08 22:04

from django.db import migrations, models
import fernet_fields.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "card_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("card_number", fernet_fields.fields.EncryptedTextField()),
                ("card_expire_date", models.CharField(max_length=10)),
                ("card_cvv", fernet_fields.fields.EncryptedTextField()),
                ("card_issue_date", models.DateField()),
                ("card_holder_id", models.UUIDField()),
                ("card_status", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
