# Generated by Django 4.2.3 on 2023-07-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creditcards", "0003_card_card_name_card_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_status",
            field=models.CharField(default="NEW", max_length=10),
        ),
    ]
