# Generated by Django 4.2.3 on 2023-07-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creditcards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_issue_date",
            field=models.CharField(max_length=10),
        ),
    ]
